apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 2
  selector:
    matchLabels:
      app: fastapi-ml
  template:
    metadata:
      name: fastapi-ml
      labels:
        app: fastapi-ml
    spec:
      containers:
        - image: mikhailmar/prediction-service:pr-1
          name: fastapi-ml
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: "gs://test-cluster-prod-bucket/models/heart_model_1.pkl"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/service-account.json"
          volumeMounts:
            - mountPath: "/var/my-app"
              name: gcp-cred
              readOnly: true
      volumes:
        - name: gcp-cred
          secret:
            secretName: service-account


